project:
  type: website
  output-dir: docs

website:
  title: "Quantitative Fisheries Notes"
  navbar:
    left:
      - href: index.html


format:
  html:
    theme: cosmo
    css: "style.css"

editor: visual

