project:
  type: website
  output-dir: docs

website:
  title: "Quantitative Fisheries Notes"
  navbar:
    left:
      - href: index.html
      - text: Numerical Methods
        href: num_meths/num_meths.html
      - text: Stock Assessment
        href: stock_assess/stock_assess_home.html



format:
  html:
    theme: cosmo
    css: "style.css"

editor: visual

